// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjxuKx30JRgZRG5SWyOFtEWsRrF1r_co',
    appId: '1:864979396886:web:a135bbc6aa3416c62b0837',
    messagingSenderId: '864979396886',
    projectId: 'event-management-53181',
    authDomain: 'event-management-53181.firebaseapp.com',
    storageBucket: 'event-management-53181.firebasestorage.app',
    measurementId: 'G-K4G9WWCSMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3I4XGCQyacWEkMfVFE-5pWmePm2N85WY',
    appId: '1:864979396886:android:bf2328aa39cae3a82b0837',
    messagingSenderId: '864979396886',
    projectId: 'event-management-53181',
    storageBucket: 'event-management-53181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaMn3q6irKW2q4owQwNYqTjoM7OHLozXI',
    appId: '1:864979396886:ios:a305f69ea945b8822b0837',
    messagingSenderId: '864979396886',
    projectId: 'event-management-53181',
    storageBucket: 'event-management-53181.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaMn3q6irKW2q4owQwNYqTjoM7OHLozXI',
    appId: '1:864979396886:ios:a305f69ea945b8822b0837',
    messagingSenderId: '864979396886',
    projectId: 'event-management-53181',
    storageBucket: 'event-management-53181.firebasestorage.app',
    iosBundleId: 'com.example.eventManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfjxuKx30JRgZRG5SWyOFtEWsRrF1r_co',
    appId: '1:864979396886:web:3133847d38be1da22b0837',
    messagingSenderId: '864979396886',
    projectId: 'event-management-53181',
    authDomain: 'event-management-53181.firebaseapp.com',
    storageBucket: 'event-management-53181.firebasestorage.app',
    measurementId: 'G-5ML88MP6KN',
  );
}
